repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff  # linter
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      - id: ruff-format  # formatter
        types_or: [ python, pyi, jupyter ]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.352
    hooks:
    - id: pyright
      language: system  # to not have to create another environment with jax
